### ISSUE TITLE
Sometimes game breaks

### ISSUE THREAD

**Issue by Bedirhanium** [Some-Bunny/Modular#1]
![image](https://github.com/Some-Bunny/Modular/assets/146653837/6e4a0e50-8cc2-42c6-b6f2-c2afbe268ad3)

Sometimes this happens and game crashes. In some situations, it happens WITHOUT ANY REASON AT ALL. I once didnt pick a single item and upon reaching the next floor, this happened. Apart from "randomness", i think interacting with mechanics that force you to somewhat hold a "gun" also breaks your game. For example giving yourself a weapon through commands, hence it "forces" you to hold another weapon even for a splitsecond and breaks the game. Or some active items, (i only know of one, there was an 'automatic gun' type of thing that could be placed on the ground to use), which make you hold a weapon and hence break the game again.

Another instance where the game crashes is, as far as i know, if you pick up "Glass" from the "master bullet shop". When i picked it up, my MAP completely broke, not being able to teleport nor move to anywhere in map, my map wasnt even following me and upon going to the next floor, of course, it crashed.

Another thing is, when the game crashes and i come back, "continue" isnt possible. This is probably intended? But if it isnt, i'd be glad if it could be continueable. Maybe some sort of self-fix thing where upon "continueing" a run, it resets all the progression you got in the last floor and makes you start from that floor again? tho this is not a bug fix, just a suggestion, crashes happen WAY TOO FREQUENTLY in modular and having a continue button would help so much. 

Thanks!

**Comment by Some-Bunny** [comment]
The error shown here should realistically not happen unless you either:
1: Somehow dropped the item (Which is impossible as its undroppable)
2: Spawned the item in via commands (Dont do that then)
3: Some secret third option in not aware of, and not being told

Modular works fine with guns being "forced" into their inventory. That is how boss pedestals work and from my own experience Modular forcefully *drops* the weapon if its allowed to. 
Bugs that are caused by or related to other mods is something I cannot do much about if at all.

The map functioning weirdly after entering the Blue Portal is not a bug. While in the blue portal, you should not be able to open your minimap, to prevent bugs with teleporting yourself out with Teleporters. The bug with the floor not loading may not even be related to the "Glass" perk in any way, as you are running multiple mods by the sounds of it. 

For cases like this send your entire output log.

Also the "Continue" feature in Gungeon is just kinda unreliable in general, and Modular also does not work with Save & Quit in any way.

**Comment by Bedirhanium** [comment]
The next time this happens, i'll make sure to send the entire output log. Sadly this happens way too often without even anything happening visually;

Sometimes the modular item stops working and i think to myself "oh lol, its gonna crash isnt it?" and crashes at the start of the next floor

About the "Glass" item, i just picked up Glass and it worked fine, it was probably the combined conflict of many stuff AND glass that caused the previous crash, or something like that :P 

I play lots of gungeon daily and i'll be doing a lot of bug reports nowadays, tho i'll make sure i can replicate the bug again before reporting. Apart from that, i heard you're retired, or semi-retired, if thats the case i wouldnt want to bother you with the bug reports, are you fine with the bug reports or would you rather be unbothered?
