### ISSUE TITLE
Game Crash seemingly out of nowhere

### ISSUE THREAD

**Issue by Bedirhanium** [Some-Bunny/Modular#3]
[LogOutput.log](https://github.com/Some-Bunny/Modular/files/14919293/LogOutput.log)

This is the output log, tho the game has stayed open for a while in the loading screen so the file has gotten big lol. 

What seems to be the cause of this crash?

**Comment by Some-Bunny** [comment]
how long did you stay on the loading screen on, though tbh im genuinely not bothered to continue this because it just looks like you closed the game normally here instead of it being a crash as the many errors at the end of the log usually appear when the game is closed manually and crashes dont do that iirc.
